### ISSUE TITLE
Some issues

### ISSUE THREAD

**Issue by cssobral2013** [m-casanova/PublicaIgnominia#6]
I report some issues with this font:

- The zeroes in percent, perthousand are overlapping the slash, mainly in Black/BlackItalic master;
- The figures aren't properly monospaced;
- The figures 0-9 in Thin/ThinItalic are overly spaced (I dunno if is this intended, because this font uses tabular figures as default whereas stock Public Sans don't);
- The 1.lf should match the stock 1 (for example, copied from tabular 1, then adapted).

**Comment by m-casanova** [comment]
Variable % (percent)

![percent_PI](https://github.com/user-attachments/assets/38e67b7f-09e3-47eb-8e5c-c71daedcabec)

Variable 010 with pnum

![010_PI](https://github.com/user-attachments/assets/266db8fb-ab3c-4410-aa58-1d5dcb9019dc)

**Comment by m-casanova** [comment]
New release 1.153:
* fixed 1.pnum
* fixed percent and all fractions

**Comment by cssobral2013** [comment]
@m-casanova - If you need more info regarding the tabular figures not being properly monospaced, see screenshots below. Highlighted are the tabular figures, that have 3500 advance width in every master. As you can see below, the AWs are different in Italic (last two) than in Roman (first two).
![Captura de tela 2024-08-04 180508](https://github.com/user-attachments/assets/6b1b41cc-d852-48c7-8f5d-a198a1e34562)
![Captura de tela 2024-08-04 180413](https://github.com/user-attachments/assets/a15875cc-a6c7-43f7-b5af-455fde977d90)
![Captura de tela 2024-08-04 180435](https://github.com/user-attachments/assets/9a74a844-a507-4f24-b331-e67a077baf3a)
![Captura de tela 2024-08-04 180452](https://github.com/user-attachments/assets/052447dc-2946-4e87-9240-20cb840ba45f)

**Comment by m-casanova** [comment]
@cssobral2013 
Many thanks. Static files were fine, but the variable file had issues with the width of many combined characters.
I should have fixed this with version 1.159.
